// frontend/src/vue/shell/CommandPalette.vue
<template>
  <div
    v-if="open"
    class="cmdk-overlay"
    role="presentation"
    @click="onClose?.()"
  >
    <div
      class="cmdk"
      role="dialog"
      aria-modal="true"
      aria-label="Быстрый переход"
      @click.stop
    >
      <div class="cmdk__search">
        <ShellIcon name="search" :size="16" />
        <input
          ref="inputEl"
          :value="query"
          placeholder="Найти задачу, сделку или страницу…"
          aria-label="Быстрый переход"
          @input="onQueryChange?.($event.target.value)"
        />
        <kbd>esc</kbd>
      </div>

      <div class="cmdk__list" role="listbox">
        <p v-if="groups.length === 0" class="cmdk__empty">Ничего не найдено</p>
        <template v-else>
          <div v-for="group in groups" :key="group.name" class="cmdk__group">
            <p class="cmdk__group-label">{{ group.name }}</p>
            <button
              v-for="item in group.items"
              :key="item.id"
              type="button"
              role="option"
              :aria-selected="item.index === activeIndex"
              class="cmdk__item"
              :class="{ 'cmdk__item--active': item.index === activeIndex }"
              @mouseenter="onActiveChange?.(item.index)"
              @click="onSelect?.(item.id)"
            >
              <ShellIcon :name="item.iconKey || 'layout'" :size="16" />
              <span class="cmdk__item-label">
                <span>{{ item.label }}</span>
                <small v-if="item.hint" class="cmdk__item-hint">{{ item.hint }}</small>
              </span>
              <ShellIcon name="arrow-right" :size="14" class="cmdk__item-arrow" />
            </button>
          </div>
        </template>
      </div>

      <footer class="cmdk__footer">
        <span><kbd>↑↓</kbd> навигация</span>
        <span><kbd>↵</kbd> открыть</span>
        <span><kbd>esc</kbd> закрыть</span>
      </footer>
    </div>
  </div>
</template>

<script setup>
import { nextTick, ref, watch } from 'vue'
import ShellIcon from './ShellIcon.vue'

const props = defineProps({
  open: { type: Boolean, default: false },
  query: { type: String, default: '' },
  groups: { type: Array, default: () => [] },
  activeIndex: { type: Number, default: 0 },
  onClose: { type: Function, default: null },
  onQueryChange: { type: Function, default: null },
  onActiveChange: { type: Function, default: null },
  onSelect: { type: Function, default: null },
})

const inputEl = ref(null)

watch(
  () => props.open,
  async (next) => {
    if (!next) return
    await nextTick()
    inputEl.value?.focus()
  },
)
</script>

// frontend/src/features/shell/components/command-palette.tsx
'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, LayoutDashboard, Search, type LucideIcon } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

export interface CommandItem {
  id: string;
  label: string;
  hint?: string;
  href?: string;
  icon?: LucideIcon;
  group: string;
  keywords?: string[];
  action?: () => void;
}

interface CommandPaletteProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  items: CommandItem[];
}

export function CommandPalette({ open, onOpenChange, items }: CommandPaletteProps) {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState('');
  const [activeIndex, setActiveIndex] = useState(0);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return items;
    return items.filter((item) => {
      const hay =
        `${item.label} ${item.hint ?? ''} ${(item.keywords ?? []).join(' ')}`.toLowerCase();
      return hay.includes(q);
    });
  }, [items, query]);

  useEffect(() => {
    if (!open) return;
    setQuery('');
    setActiveIndex(0);
    const id = window.setTimeout(() => inputRef.current?.focus(), 30);
    return () => window.clearTimeout(id);
  }, [open]);

  useEffect(() => {
    setActiveIndex(0);
  }, [query]);

  const runItem = useCallback(
    (item: CommandItem) => {
      onOpenChange(false);
      if (item.action) item.action();
      else if (item.href) router.push(item.href);
    },
    [onOpenChange, router],
  );

  useEffect(() => {
    if (!open) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.preventDefault();
        onOpenChange(false);
      }
      if (event.key === 'ArrowDown') {
        event.preventDefault();
        setActiveIndex((i) => Math.min(i + 1, Math.max(filtered.length - 1, 0)));
      }
      if (event.key === 'ArrowUp') {
        event.preventDefault();
        setActiveIndex((i) => Math.max(i - 1, 0));
      }
      if (event.key === 'Enter' && filtered[activeIndex]) {
        event.preventDefault();
        runItem(filtered[activeIndex]);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, filtered, activeIndex, onOpenChange, runItem]);

  const groups = useMemo(() => {
    const map = new Map<string, CommandItem[]>();
    for (const item of filtered) {
      const list = map.get(item.group) ?? [];
      list.push(item);
      map.set(item.group, list);
    }
    return [...map.entries()];
  }, [filtered]);

  let flatIndex = -1;

  return (
    <AnimatePresence>
      {open ? (
        <motion.div
          className="cmdk-overlay"
          role="presentation"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.16 }}
          onClick={() => onOpenChange(false)}
        >
          <motion.div
            className="cmdk"
            role="dialog"
            aria-modal="true"
            aria-label="Командная палитра"
            initial={{ opacity: 0, y: 12, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 8, scale: 0.98 }}
            transition={{ type: 'spring', stiffness: 420, damping: 32 }}
            onClick={(event) => event.stopPropagation()}
          >
            <div className="cmdk__search">
              <Search size={16} strokeWidth={1.75} aria-hidden="true" />
              <input
                ref={inputRef}
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Перейти, создать, найти…"
                aria-label="Поиск команд"
              />
              <kbd>esc</kbd>
            </div>

            <div className="cmdk__list" role="listbox">
              {filtered.length === 0 ? (
                <p className="cmdk__empty">Ничего не найдено</p>
              ) : (
                groups.map(([group, groupItems]) => (
                  <div key={group} className="cmdk__group">
                    <p className="cmdk__group-label">{group}</p>
                    {groupItems.map((item) => {
                      flatIndex += 1;
                      const index = flatIndex;
                      const Icon = item.icon ?? LayoutDashboard;
                      const active = index === activeIndex;
                      return (
                        <button
                          key={item.id}
                          type="button"
                          role="option"
                          aria-selected={active}
                          className={`cmdk__item${active ? ' cmdk__item--active' : ''}`}
                          onMouseEnter={() => setActiveIndex(index)}
                          onClick={() => runItem(item)}
                        >
                          <Icon size={16} strokeWidth={1.75} aria-hidden="true" />
                          <span className="cmdk__item-label">{item.label}</span>
                          {item.hint ? <kbd>{item.hint}</kbd> : null}
                          <ArrowRight size={14} className="cmdk__item-arrow" aria-hidden="true" />
                        </button>
                      );
                    })}
                  </div>
                ))
              )}
            </div>

            <footer className="cmdk__footer">
              <span>
                <kbd>↑↓</kbd> навигация
              </span>
              <span>
                <kbd>↵</kbd> открыть
              </span>
              <span>
                <kbd>esc</kbd> закрыть
              </span>
            </footer>
          </motion.div>
        </motion.div>
      ) : null}
    </AnimatePresence>
  );
}
