// frontend/src/vue/templates/ApplyTaskTemplateControl.vue
<template>
  <div v-if="templates.length > 0" class="task-drawer__field">
    <span class="task-drawer__label">
      Шаблон
      <FieldHint
        text="Заполнит пустые поля и добавит теги, сабтаски и DoD из шаблона. Уже заполненные поля не перезаписываются."
      />
    </span>
    <div class="task-checklist__apply" role="group" aria-label="Применить шаблон задачи">
      <select v-model="localTemplateId" aria-label="Шаблон задачи">
        <option value="">Применить шаблон…</option>
        <option v-for="template in templates" :key="template.id" :value="template.id">
          {{ template.name }}
        </option>
      </select>
      <button
        type="button"
        :disabled="!localTemplateId || isPending"
        @click="apply"
      >
        {{ isPending ? '…' : 'Применить' }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue'
import FieldHint from '../boards/FieldHint.vue'

const props = defineProps({
  templates: { type: Array, default: () => [] },
  isPending: { type: Boolean, default: false },
  onApply: { type: Function, default: null },
})

const localTemplateId = ref('')

watch(
  () => props.templates,
  () => {
    if (!props.templates.some((item) => item.id === localTemplateId.value)) {
      localTemplateId.value = ''
    }
  },
)

async function apply() {
  if (!localTemplateId.value) return
  try {
    await props.onApply?.(localTemplateId.value)
    localTemplateId.value = ''
  } catch {
    /* ignore */
  }
}
</script>

// frontend/src/features/templates/components/apply-task-template-control.tsx
'use client';

import { useState } from 'react';
import { FieldHint } from '@/features/boards/components/field-hint';
import { useApplyTaskTemplateMutation, useTaskTemplatesQuery } from '../hooks';

export function ApplyTaskTemplateControl({
  workspaceId,
  taskId,
}: {
  workspaceId: string;
  taskId: string;
}) {
  const { data: templates = [] } = useTaskTemplatesQuery(workspaceId);
  const applyMutation = useApplyTaskTemplateMutation(workspaceId, taskId);
  const [templateId, setTemplateId] = useState('');

  if (templates.length === 0) return null;

  return (
    <div className="task-drawer__field">
      <span className="task-drawer__label">
        Шаблон
        <FieldHint text="Заполнит пустые поля и добавит теги, сабтаски и DoD из шаблона. Уже заполненные поля не перезаписываются." />
      </span>
      <div className="task-checklist__apply" role="group" aria-label="Применить шаблон задачи">
        <select
          value={templateId}
          onChange={(event) => setTemplateId(event.target.value)}
          aria-label="Шаблон задачи"
        >
          <option value="">Применить шаблон…</option>
          {templates.map((template) => (
            <option key={template.id} value={template.id}>
              {template.name}
            </option>
          ))}
        </select>
        <button
          type="button"
          disabled={!templateId || applyMutation.isPending}
          onClick={() => {
            if (!templateId) return;
            applyMutation.mutate(templateId, { onSuccess: () => setTemplateId('') });
          }}
        >
          {applyMutation.isPending ? '…' : 'Применить'}
        </button>
      </div>
    </div>
  );
}
