// frontend/src/vue/boards/AddColumnPanel.vue
<template>
  <form class="kanban-add-column" @submit.prevent="submit">
    <span class="kanban-add-column__label">Новая колонка</span>
    <input
      v-model="name"
      placeholder="Название колонки"
      maxlength="80"
      class="kanban-add-column__input"
    />
    <button type="submit" class="kanban-add-column__btn" :disabled="!name.trim() || pending">
      {{ pending ? 'Добавление...' : '+ Добавить колонку' }}
    </button>
  </form>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  pending: { type: Boolean, default: false },
  onCreate: { type: Function, default: null },
})

const name = ref('')

async function submit() {
  const next = name.value.trim()
  if (!next) return
  await props.onCreate?.(next)
  name.value = ''
}
</script>

// frontend/src/features/boards/components/kanban/add-column-panel.tsx
'use client';

import { FormEvent, useState } from 'react';
import { useCreateColumnMutation } from '../../hooks';

export function AddColumnPanel({ workspaceId, boardId }: { workspaceId: string; boardId: string }) {
  const createColumnMutation = useCreateColumnMutation(workspaceId, boardId);
  const [name, setName] = useState('');

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!name.trim()) return;
    await createColumnMutation.mutateAsync(name.trim());
    setName('');
  };

  return (
    <form onSubmit={handleSubmit} className="kanban-add-column">
      <span className="kanban-add-column__label">Новая колонка</span>
      <input
        value={name}
        onChange={(event) => setName(event.target.value)}
        placeholder="Название колонки"
        maxLength={80}
        className="kanban-add-column__input"
      />
      <button
        type="submit"
        disabled={!name.trim() || createColumnMutation.isPending}
        className="kanban-add-column__btn"
      >
        {createColumnMutation.isPending ? 'Добавление...' : '+ Добавить колонку'}
      </button>
    </form>
  );
}
