// frontend/src/vue/boards/KanbanTaskCardMeta.vue
<template>
  <div v-if="visible" class="kanban-task-meta">
    <span
      v-for="tag in tags"
      :key="tag.id"
      class="tag-chip"
      :style="{ background: tag.color + '22', color: tag.color, borderColor: tag.color }"
    >
      <i :style="{ background: tag.color }" />
      {{ tag.name }}
    </span>

    <span v-if="subtaskTotal > 0" class="kanban-task-chip">
      {{ subtaskCompleted }}/{{ subtaskTotal }} шагов
    </span>

    <span v-if="overdueLabel" :class="overdueChipClass">{{ overdueLabel }}</span>

    <span v-if="recurrenceLabel" class="kanban-task-chip kanban-task-chip--recurrence">
      {{ recurrenceLabel }}
    </span>

    <span v-if="assigneeName" class="kanban-task-chip">{{ assigneeName }}</span>

    <span
      v-if="priorityLabel"
      :class="'kanban-task-chip kanban-task-chip--priority-' + priority"
    >
      {{ priorityLabel }}
    </span>

    <span v-if="complexity" class="kanban-task-chip">{{ complexity }} SP</span>

    <span v-if="estimateLabel" class="kanban-task-chip kanban-task-chip--estimate">
      {{ estimateLabel }}
    </span>

    <span v-if="actualLabel" class="kanban-task-chip kanban-task-chip--actual">
      факт {{ actualLabel }}
    </span>

    <span v-if="timerRunning" class="kanban-task-chip kanban-task-chip--timer">
      таймер запущен
    </span>

    <span v-if="completed" class="kanban-task-chip kanban-task-chip--complete">выполнено</span>

    <span v-if="dueLabel" :class="dueChipClass">{{ dueLabel }}</span>

    <span
      v-for="chip in customFieldChips"
      :key="chip.id"
      class="kanban-task-chip kanban-task-chip--custom"
    >
      {{ chip.label }}
    </span>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  tags: { type: Array, default: () => [] },
  subtaskTotal: { type: Number, default: 0 },
  subtaskCompleted: { type: Number, default: 0 },
  overdueLabel: { type: String, default: '' },
  agingLevel: { type: String, default: 'none' },
  recurrenceLabel: { type: String, default: '' },
  assigneeName: { type: String, default: '' },
  priority: { type: String, default: '' },
  priorityLabel: { type: String, default: '' },
  complexity: { type: [String, Number], default: '' },
  estimateLabel: { type: String, default: '' },
  actualLabel: { type: String, default: '' },
  timerRunning: { type: Boolean, default: false },
  completed: { type: Boolean, default: false },
  dueLabel: { type: String, default: '' },
  isOverdue: { type: Boolean, default: false },
  customFieldChips: { type: Array, default: () => [] },
})

const visible = computed(
  () =>
    Boolean(props.priority) ||
    Boolean(props.complexity) ||
    Boolean(props.estimateLabel) ||
    Boolean(props.actualLabel) ||
    props.timerRunning ||
    props.completed ||
    Boolean(props.dueLabel) ||
    Boolean(props.recurrenceLabel) ||
    Boolean(props.overdueLabel) ||
    props.tags.length > 0 ||
    props.subtaskTotal > 0 ||
    props.customFieldChips.length > 0 ||
    Boolean(props.assigneeName),
)

const overdueChipClass = computed(() =>
  props.agingLevel === 'due-today' || props.agingLevel === 'due-soon'
    ? 'kanban-task-chip kanban-task-chip--due-soon'
    : 'kanban-task-chip kanban-task-chip--overdue',
)

const dueChipClass = computed(() =>
  props.isOverdue ? 'kanban-task-chip kanban-task-chip--overdue-date' : 'kanban-task-chip',
)
</script>

// frontend/src/features/boards/components/kanban/kanban-task-card-meta.tsx
'use client';

import { formatMinutes } from '@/shared/lib/format-duration';
import { PRIORITY_LABELS, type BoardTask, type TaskTag } from '../../types';

const EMPTY_TAGS: TaskTag[] = [];
const EMPTY_SUBTASKS: NonNullable<BoardTask['subtasks']> = [];

export function KanbanTaskCardMeta({
  task,
  dueLabel,
  recurrenceLabel,
  overdueLabel,
  agingLevel,
  isOverdue,
  customFieldChips,
}: {
  task: BoardTask;
  dueLabel: string | null;
  recurrenceLabel: string | null;
  overdueLabel: string | null;
  agingLevel: string;
  isOverdue: boolean;
  customFieldChips: Array<{ id: string; label: string }>;
}) {
  const tags = task.tags ?? EMPTY_TAGS;
  const subtasks = task.subtasks ?? EMPTY_SUBTASKS;
  const subtaskTotal = task.subtaskStats?.total ?? subtasks.length;
  const subtaskCompleted =
    task.subtaskStats?.completed ?? subtasks.filter((item) => item.completed).length;

  if (!(
    task.priority ||
    task.complexity ||
    task.timeEstimateMinutes ||
    task.actualMinutes ||
    task.timerStartedAt ||
    task.completedAt ||
    dueLabel ||
    recurrenceLabel ||
    overdueLabel ||
    tags.length > 0 ||
    subtaskTotal > 0 ||
    customFieldChips.length > 0 ||
    task.assignee
  )) {
    return null;
  }

  return (
    <div className="kanban-task-meta">
      {tags.slice(0, 3).map((tag) => (
        <span
          key={tag.id}
          className="tag-chip"
          style={{ background: `${tag.color}22`, color: tag.color, borderColor: tag.color }}
        >
          <i style={{ background: tag.color }} />
          {tag.name}
        </span>
      ))}
      {subtaskTotal > 0 ? (
        <span className="kanban-task-chip">
          {subtaskCompleted}/{subtaskTotal} шагов
        </span>
      ) : null}
      {overdueLabel ? (
        <span
          className={`kanban-task-chip ${
            agingLevel === 'due-today' || agingLevel === 'due-soon'
              ? 'kanban-task-chip--due-soon'
              : 'kanban-task-chip--overdue'
          }`}
        >
          {overdueLabel}
        </span>
      ) : null}
      {recurrenceLabel ? (
        <span className="kanban-task-chip kanban-task-chip--recurrence">{recurrenceLabel}</span>
      ) : null}
      {task.assignee ? (
        <span className="kanban-task-chip">{task.assignee.name.split(' ')[0]}</span>
      ) : null}
      {task.priority ? (
        <span className={`kanban-task-chip kanban-task-chip--priority-${task.priority}`}>
          {PRIORITY_LABELS[task.priority]}
        </span>
      ) : null}
      {task.complexity ? <span className="kanban-task-chip">{task.complexity} SP</span> : null}
      {task.timeEstimateMinutes ? (
        <span className="kanban-task-chip kanban-task-chip--estimate">
          {formatMinutes(task.timeEstimateMinutes)}
        </span>
      ) : null}
      {task.actualMinutes ? (
        <span className="kanban-task-chip kanban-task-chip--actual">
          факт {formatMinutes(task.actualMinutes)}
        </span>
      ) : null}
      {task.timerStartedAt ? (
        <span className="kanban-task-chip kanban-task-chip--timer">таймер запущен</span>
      ) : null}
      {task.completedAt ? (
        <span className="kanban-task-chip kanban-task-chip--complete">выполнено</span>
      ) : null}
      {dueLabel ? (
        <span className={`kanban-task-chip ${isOverdue ? 'kanban-task-chip--overdue-date' : ''}`}>
          {dueLabel}
        </span>
      ) : null}
      {customFieldChips.map((chip) => (
        <span key={chip.id} className="kanban-task-chip kanban-task-chip--custom">
          {chip.label}
        </span>
      ))}
    </div>
  );
}
