// frontend/src/vue/boards/TaskDrawerHeader.vue
<template>
  <div class="task-drawer__header">
    <div>
      <p class="task-drawer__eyebrow">{{ columnName }}</p>
      <h2 class="task-drawer__heading">Задача</h2>
    </div>
    <button
      type="button"
      class="dashboard-header__icon-btn"
      aria-label="Закрыть"
      @click="onClose?.()"
    >
      ×
    </button>
  </div>
</template>

<script setup>
defineProps({
  columnName: { type: String, default: '' },
  onClose: { type: Function, default: null },
})
</script>

// frontend/src/features/boards/components/task-drawer/task-drawer-header.tsx
'use client';

export function TaskDrawerHeader({
  columnName,
  onClose,
}: {
  columnName: string;
  onClose: () => void;
}) {
  return (
    <div className="task-drawer__header">
      <div>
        <p className="task-drawer__eyebrow">{columnName}</p>
        <h2 className="task-drawer__heading">Задача</h2>
      </div>
      <button
        type="button"
        className="dashboard-header__icon-btn"
        onClick={onClose}
        aria-label="Закрыть"
      >
        ×
      </button>
    </div>
  );
}
