// frontend/src/vue/boards/TaskPlanningFields.vue
<template>
  <div class="task-drawer__grid">
    <label class="task-drawer__field">
      <span class="task-drawer__label">
        Спринт
        <FieldHint text="Короткий рабочий цикл (обычно 1–2 недели), в который входит задача." />
      </span>
      <select class="glass-input" :value="sprintId" @change="onSprintChange?.($event.target.value)">
        <option value="">Без спринта</option>
        <option v-for="sprint in sprints" :key="sprint.id" :value="sprint.id">
          {{ sprint.name }}
        </option>
      </select>
    </label>

    <label class="task-drawer__field">
      <span class="task-drawer__label">
        Эпик
        <FieldHint text="Крупная цель. Задачу можно вложить в эпик или отметить саму как эпик." />
      </span>
      <select
        class="glass-input"
        :value="isEpic ? '' : epicId"
        :disabled="isEpic"
        @change="onEpicChange?.($event.target.value)"
      >
        <option value="">Без эпика</option>
        <option v-for="epic in epicOptions" :key="epic.id" :value="epic.id">
          {{ epic.title }}
        </option>
      </select>
      <label class="forms-editor__checkbox" style="margin-top: 0.5rem">
        <input type="checkbox" :checked="isEpic" @change="onIsEpicToggle" />
        Это эпик
      </label>
    </label>
  </div>
</template>

<script setup>
import FieldHint from './FieldHint.vue';

const props = defineProps({
  sprintId: { type: String, default: '' },
  epicId: { type: String, default: '' },
  isEpic: { type: Boolean, default: false },
  sprints: { type: Array, default: () => [] },
  epicOptions: { type: Array, default: () => [] },
  onSprintChange: { type: Function, default: null },
  onEpicChange: { type: Function, default: null },
  onIsEpicChange: { type: Function, default: null },
});

function onIsEpicToggle(event) {
  const checked = event.target.checked;
  props.onIsEpicChange?.(checked);
  if (checked) props.onEpicChange?.('');
}
</script>

// frontend/src/features/boards/components/task-drawer/task-planning-fields.tsx
'use client';

import { useMemo } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { EpicAiBreakdown } from '@/features/ai';
import { useSprintsQuery } from '@/features/sprints';
import { boardKeys, invalidateWorkspaceBoards } from '../../hooks';
import type { BoardTask, BoardView, TaskRelationCandidate } from '../../types';
import { FieldHint } from '../field-hint';

export function TaskPlanningFields({
  workspaceId,
  task,
  relationCandidates,
  sprintId,
  epicId,
  isEpic,
  onSprintChange,
  onEpicChange,
  onIsEpicChange,
}: {
  workspaceId: string;
  task: BoardTask;
  relationCandidates: TaskRelationCandidate[];
  sprintId: string;
  epicId: string;
  isEpic: boolean;
  onSprintChange: (id: string) => void;
  onEpicChange: (id: string) => void;
  onIsEpicChange: (value: boolean) => void;
}) {
  const queryClient = useQueryClient();
  const { data: sprints = [] } = useSprintsQuery(workspaceId);
  const cachedBoard = queryClient.getQueryData<BoardView>(boardKeys.detail(workspaceId, 'default'));
  const epicOptions = useMemo(() => {
    const fromCandidates = relationCandidates.filter(
      (candidate) => candidate.isEpic && candidate.id !== task.id,
    );
    if (fromCandidates.length > 0) {
      return fromCandidates.map((candidate) => ({ id: candidate.id, title: candidate.title }));
    }
    return (cachedBoard?.columns.flatMap((column) => column.tasks) ?? [])
      .filter((item) => item.isEpic && item.id !== task.id)
      .map((item) => ({ id: item.id, title: item.title }));
  }, [cachedBoard, relationCandidates, task.id]);

  return (
    <div className="task-drawer__grid">
      <label className="task-drawer__field">
        <span className="task-drawer__label">
          Спринт
          <FieldHint text="Короткий рабочий цикл (обычно 1–2 недели), в который входит задача." />
        </span>
        <select
          value={sprintId}
          onChange={(event) => onSprintChange(event.target.value)}
          className="glass-input"
        >
          <option value="">Без спринта</option>
          {sprints
            .filter((sprint) => !sprint.closedAt || sprint.id === sprintId)
            .map((sprint) => (
              <option key={sprint.id} value={sprint.id}>
                {sprint.name}
              </option>
            ))}
        </select>
      </label>

      <label className="task-drawer__field">
        <span className="task-drawer__label">
          Эпик
          <FieldHint text="Крупная цель. Задачу можно вложить в эпик или отметить саму как эпик." />
        </span>
        <select
          value={isEpic ? '' : epicId}
          onChange={(event) => onEpicChange(event.target.value)}
          className="glass-input"
          disabled={isEpic}
        >
          <option value="">Без эпика</option>
          {epicOptions.map((epic) => (
            <option key={epic.id} value={epic.id}>
              {epic.title}
            </option>
          ))}
        </select>
        <label className="forms-editor__checkbox" style={{ marginTop: '0.5rem' }}>
          <input
            type="checkbox"
            checked={isEpic}
            onChange={(event) => {
              onIsEpicChange(event.target.checked);
              if (event.target.checked) onEpicChange('');
            }}
          />
          Это эпик
        </label>
        {task.isEpic ? (
          <EpicAiBreakdown
            workspaceId={workspaceId}
            epicId={task.id}
            onApplied={() => {
              invalidateWorkspaceBoards(queryClient, workspaceId);
              void queryClient.invalidateQueries({ queryKey: ['all-tasks', workspaceId] });
            }}
          />
        ) : null}
      </label>
    </div>
  );
}
