// frontend/src/vue/workspaces/InviteMemberForm.vue
<template>
  <form class="space-y-3" @submit.prevent="onSubmit">
    <div class="settings-invite-grid">
      <input
        v-model="email"
        type="email"
        required
        placeholder="email@company.com"
        class="glass-input"
      />
      <select v-model="role" class="glass-input">
        <option v-for="option in roleOptions" :key="option.value" :value="option.value">
          {{ option.label }}
        </option>
      </select>
      <button type="submit" class="btn-primary" :disabled="isPending">
        {{ isPending ? 'Отправка...' : 'Пригласить' }}
      </button>
    </div>

    <p v-if="errorMessage" class="text-sm text-red-400">{{ errorMessage }}</p>
    <p v-if="inviteLink" class="break-all text-sm text-muted-foreground">
      Ссылка приглашения: {{ inviteLink }}
    </p>
  </form>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  roleOptions: { type: Array, required: true },
  isPending: { type: Boolean, default: false },
  errorMessage: { type: String, default: '' },
  inviteLink: { type: String, default: '' },
  onInvite: { type: Function, required: true },
})

const email = ref('')
const role = ref('MEMBER')

async function onSubmit() {
  const trimmed = email.value.trim()
  if (!trimmed) return

  try {
    await props.onInvite({ email: trimmed, role: role.value })
    email.value = ''
  } catch {
    /* errorMessage from React */
  }
}
</script>

// frontend/src/features/workspaces/components/invite-member-form.tsx
'use client';

import { FormEvent, useState } from 'react';
import { useCreateInvitationMutation } from '../hooks';
import type { WorkspaceRole } from '../types';

interface InviteMemberFormProps {
  workspaceId: string;
}

export function InviteMemberForm({ workspaceId }: InviteMemberFormProps) {
  const [email, setEmail] = useState('');
  const [role, setRole] = useState<WorkspaceRole>('MEMBER');
  const [inviteLink, setInviteLink] = useState<string | null>(null);
  const inviteMutation = useCreateInvitationMutation(workspaceId);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setInviteLink(null);

    const result = await inviteMutation.mutateAsync({ email, role });

    if (result?.token) {
      const link = `${window.location.origin}/invite/${result.token}`;
      setInviteLink(link);
      setEmail('');
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-3">
      <div className="settings-invite-grid">
        <input
          type="email"
          required
          placeholder="email@company.com"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          className="glass-input"
        />
        <select
          value={role}
          onChange={(event) => setRole(event.target.value as WorkspaceRole)}
          className="glass-input"
        >
          <option value="VIEWER">Viewer</option>
          <option value="MEMBER">Member</option>
          <option value="ADMIN">Admin</option>
        </select>
        <button type="submit" disabled={inviteMutation.isPending} className="btn-primary">
          {inviteMutation.isPending ? 'Отправка...' : 'Пригласить'}
        </button>
      </div>

      {inviteMutation.error ? (
        <p className="text-sm text-red-400">{inviteMutation.error.message}</p>
      ) : null}

      {inviteLink ? (
        <p className="break-all text-sm text-muted-foreground">Ссылка приглашения: {inviteLink}</p>
      ) : null}
    </form>
  );
}
