// frontend/src/vue/workspaces/InvitationsList.vue
<template>
  <p v-if="isLoading" class="text-sm text-muted-foreground">Загрузка приглашений...</p>

  <p v-else-if="invitations.length === 0" class="text-sm text-muted-foreground">
    Активных приглашений нет.
  </p>

  <ul v-else class="settings-invite-list">
    <li v-for="invitation in invitations" :key="invitation.id" class="settings-invite-item">
      <div>
        <p class="text-sm font-medium">{{ invitation.email }}</p>
        <p class="text-xs text-muted-foreground">
          {{ invitation.role }} · до {{ formatExpiresAt(invitation.expiresAt) }}
        </p>
      </div>
      <button
        type="button"
        class="text-sm text-red-400 hover:text-red-300"
        :disabled="isRevoking && pendingId === invitation.id"
        @click="emit('revoke', invitation.id)"
      >
        {{ isRevoking && pendingId === invitation.id ? '…' : 'Отозвать' }}
      </button>
    </li>
  </ul>
</template>

<script setup>
defineProps({
  invitations: { type: Array, required: true },
  isLoading: { type: Boolean, default: false },
  isRevoking: { type: Boolean, default: false },
  pendingId: { type: String, default: null },
})

const emit = defineEmits(['revoke'])

function formatExpiresAt(value) {
  return new Date(value).toLocaleDateString('ru-RU')
}
</script>

// frontend/src/features/workspaces/components/invitations-list.tsx
'use client';

import { useInvitationsQuery, useRevokeInvitationMutation } from '../hooks';

interface InvitationsListProps {
  workspaceId: string;
}

export function InvitationsList({ workspaceId }: InvitationsListProps) {
  const { data: invitations = [], isLoading } = useInvitationsQuery(workspaceId);
  const revokeMutation = useRevokeInvitationMutation(workspaceId);

  if (isLoading) {
    return <p className="text-sm text-muted-foreground">Загрузка приглашений...</p>;
  }

  if (!invitations.length) {
    return <p className="text-sm text-muted-foreground">Активных приглашений нет.</p>;
  }

  return (
    <ul className="settings-invite-list">
      {invitations.map((invitation) => (
        <li key={invitation.id} className="settings-invite-item">
          <div>
            <p className="text-sm font-medium">{invitation.email}</p>
            <p className="text-xs text-muted-foreground">
              {invitation.role} · до {new Date(invitation.expiresAt).toLocaleDateString('ru-RU')}
            </p>
          </div>
          <button
            type="button"
            onClick={() => revokeMutation.mutate(invitation.id)}
            disabled={revokeMutation.isPending}
            className="text-sm text-red-400 hover:text-red-300"
          >
            Отозвать
          </button>
        </li>
      ))}
    </ul>
  );
}
