// frontend/src/features/boards/components/kanban/kanban-column-add-task-form.tsx
'use client';

import { FormEvent, useState } from 'react';
import { useTaskTemplatesQuery } from '@/features/templates';
import { useCreateTaskMutation } from '../../hooks';

export function KanbanColumnAddTaskForm({
  workspaceId,
  boardId,
  columnId,
}: {
  workspaceId: string;
  boardId: string;
  columnId: string;
}) {
  const createMutation = useCreateTaskMutation(workspaceId, boardId);
  const { data: taskTemplates = [] } = useTaskTemplatesQuery(workspaceId);
  const [title, setTitle] = useState('');
  const [templateId, setTemplateId] = useState('');

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const selected = taskTemplates.find((template) => template.id === templateId);
    const nextTitle = title.trim() || selected?.title?.trim() || '';
    if (!nextTitle) return;
    await createMutation.mutateAsync({
      title: nextTitle,
      columnId,
      ...(templateId ? { templateId } : {}),
    });
    setTitle('');
    setTemplateId('');
  };

  return (
    <form onSubmit={handleSubmit} className="kanban-column__add">
      {taskTemplates.length > 0 ? (
        <select
          className="kanban-column__add-template"
          value={templateId}
          onChange={(event) => {
            const nextId = event.target.value;
            setTemplateId(nextId);
            const selected = taskTemplates.find((template) => template.id === nextId);
            if (selected?.title && !title.trim()) {
              setTitle(selected.title);
            }
          }}
          aria-label="Шаблон задачи"
        >
          <option value="">Без шаблона</option>
          {taskTemplates.map((template) => (
            <option key={template.id} value={template.id}>
              {template.name}
            </option>
          ))}
        </select>
      ) : null}
      <input
        value={title}
        onChange={(event) => setTitle(event.target.value)}
        placeholder="Задача..."
        className="kanban-column__add-input"
      />
      <button
        type="submit"
        disabled={
          createMutation.isPending ||
          !(title.trim() || taskTemplates.find((template) => template.id === templateId)?.title)
        }
        className="kanban-column__add-btn"
        aria-label="Добавить задачу"
      >
        +
      </button>
    </form>
  );
}

// frontend/src/vue/boards/KanbanColumnAddTaskForm.vue
<template>
  <form class="kanban-column__add" @submit.prevent="submit">
    <select
      v-if="templates.length"
      class="kanban-column__add-template"
      :value="templateId"
      aria-label="Шаблон задачи"
      @change="onTemplateChange"
    >
      <option value="">Без шаблона</option>
      <option v-for="template in templates" :key="template.id" :value="template.id">
        {{ template.name }}
      </option>
    </select>

    <input
      :value="title"
      placeholder="Задача..."
      class="kanban-column__add-input"
      @input="title = $event.target.value"
    />

    <button
      type="submit"
      class="kanban-column__add-btn"
      aria-label="Добавить задачу"
      :disabled="pending || !canSubmit"
    >
      +
    </button>
  </form>
</template>

<script setup>
import { computed, ref } from 'vue'

const props = defineProps({
  templates: { type: Array, default: () => [] },
  pending: { type: Boolean, default: false },
  onCreate: { type: Function, default: null },
})

const title = ref('')
const templateId = ref('')

const canSubmit = computed(() => {
  if (title.value.trim()) return true
  const selected = props.templates.find((template) => template.id === templateId.value)
  return Boolean(selected?.title?.trim())
})

function onTemplateChange(event) {
  const nextId = event.target.value
  templateId.value = nextId
  const selected = props.templates.find((template) => template.id === nextId)
  if (selected?.title && !title.value.trim()) {
    title.value = selected.title
  }
}

async function submit() {
  const selected = props.templates.find((template) => template.id === templateId.value)
  const nextTitle = title.value.trim() || selected?.title?.trim() || ''
  if (!nextTitle) return
  await props.onCreate?.({
    title: nextTitle,
    templateId: templateId.value || undefined,
  })
  title.value = ''
  templateId.value = ''
}
</script>
