// frontend/src/features/boards/components/kanban/kanban-drag-overlay.tsx
'use client';

import type { BoardColumn, BoardTask } from '../../types';

export function KanbanDragOverlay({
  activeColumn,
  activeTask,
}: {
  activeColumn: BoardColumn | null;
  activeTask: BoardTask | null;
}) {
  return (
    <>
      {activeColumn ? (
        <div className="kanban-column kanban-column--overlay">
          <header className="kanban-column__header">
            <h3>{activeColumn.name}</h3>
          </header>
        </div>
      ) : null}
      {activeTask ? (
        <div className="kanban-task-card kanban-task-card--dragging kanban-task">
          <p className="kanban-task-card__title">{activeTask.title}</p>
        </div>
      ) : null}
    </>
  );
}

// frontend/src/vue/boards/KanbanDragOverlay.vue
<template>
  <div v-if="columnName" class="kanban-column kanban-column--overlay">
    <header class="kanban-column__header">
      <h3>{{ columnName }}</h3>
    </header>
  </div>
  <div v-else-if="taskTitle" class="kanban-task-card kanban-task-card--dragging kanban-task">
    <p class="kanban-task-card__title">{{ taskTitle }}</p>
  </div>
</template>

<script setup>
defineProps({
  columnName: { type: String, default: '' },
  taskTitle: { type: String, default: '' },
})
</script>
