// frontend/src/features/saved-filters/components/saved-filters-control.tsx
'use client';

import { FormEvent, useEffect, useRef, useState } from 'react';
import { EMPTY_BOARD_FILTERS, type BoardFilters } from '@/features/boards/types';
import {
  useCreateSavedFilterMutation,
  useDeleteSavedFilterMutation,
  useSavedFiltersQuery,
  useUpdateSavedFilterMutation,
} from '../hooks';
import type { SavedFilter, SavedFilterView } from '../types';

interface SavedFiltersControlProps {
  workspaceId: string;
  view: SavedFilterView;
  filters: BoardFilters;
  onApply: (filters: BoardFilters) => void;

  skipDefaultApply?: boolean;
}

export function SavedFiltersControl({
  workspaceId,
  view,
  filters,
  onApply,
  skipDefaultApply = false,
}: SavedFiltersControlProps) {
  const { data: saved = [], isLoading } = useSavedFiltersQuery(workspaceId, view);
  const createMutation = useCreateSavedFilterMutation(workspaceId, view);
  const updateMutation = useUpdateSavedFilterMutation(workspaceId, view);
  const deleteMutation = useDeleteSavedFilterMutation(workspaceId, view);

  const [selectedId, setSelectedId] = useState('');
  const [saveOpen, setSaveOpen] = useState(false);
  const [saveName, setSaveName] = useState('');
  const [saveAsDefault, setSaveAsDefault] = useState(false);
  const [saveAsShared, setSaveAsShared] = useState(false);
  const appliedDefaultRef = useRef(false);

  useEffect(() => {
    appliedDefaultRef.current = false;
    setSelectedId('');
  }, [workspaceId, view]);

  useEffect(() => {
    if (skipDefaultApply || appliedDefaultRef.current || isLoading || !saved.length) return;
    const defaultFilter = saved.find((item) => item.isDefault);
    if (!defaultFilter) return;
    appliedDefaultRef.current = true;
    setSelectedId(defaultFilter.id);
    onApply(normalizeFilters(defaultFilter.filters));
  }, [isLoading, onApply, saved, skipDefaultApply]);

  const handleSelect = (filterId: string) => {
    setSelectedId(filterId);
    if (!filterId) return;
    const found = saved.find((item) => item.id === filterId);
    if (found) onApply(normalizeFilters(found.filters));
  };

  const handleSave = async (event: FormEvent) => {
    event.preventDefault();
    const name = saveName.trim();
    if (!name) return;

    const created = await createMutation.mutateAsync({
      view,
      name,
      filters,
      isDefault: saveAsDefault,
      isShared: saveAsShared,
    });
    setSaveOpen(false);
    setSaveName('');
    setSaveAsDefault(false);
    setSaveAsShared(false);
    if (created?.id) setSelectedId(created.id);
  };

  const selected = saved.find((item) => item.id === selectedId) ?? null;

  return (
    <div className="saved-filters">
      <select
        value={selectedId}
        onChange={(event) => handleSelect(event.target.value)}
        className="board-filters__select"
        aria-label="Сохранённые фильтры"
        disabled={isLoading}
      >
        <option value="">Сохранённые фильтры</option>
        {saved.map((item) => (
          <option key={item.id} value={item.id}>
            {item.isPinned ? '📌 ' : ''}
            {item.isDefault ? '★ ' : ''}
            {item.name}
            {item.isShared ? ' · общий' : ''}
          </option>
        ))}
      </select>

      <button
        type="button"
        className="board-filters__chip"
        onClick={() => setSaveOpen((open) => !open)}
      >
        Сохранить фильтр
      </button>

      {selected ? (
        <>
          {!selected.isDefault ? (
            <button
              type="button"
              className="board-filters__chip"
              disabled={updateMutation.isPending}
              onClick={() =>
                updateMutation.mutate({ filterId: selected.id, data: { isDefault: true } })
              }
            >
              По умолчанию
            </button>
          ) : null}
          <button
            type="button"
            className="board-filters__chip"
            disabled={updateMutation.isPending}
            onClick={() =>
              updateMutation.mutate({
                filterId: selected.id,
                data: { isPinned: !selected.isPinned },
              })
            }
          >
            {selected.isPinned ? 'Открепить' : 'Закрепить'}
          </button>
          <button
            type="button"
            className="board-filters__chip"
            disabled={updateMutation.isPending}
            onClick={() =>
              updateMutation.mutate({
                filterId: selected.id,
                data: { isShared: !selected.isShared },
              })
            }
          >
            {selected.isShared ? 'Скрыть' : 'Поделиться'}
          </button>
          <button
            type="button"
            className="board-filters__reset"
            disabled={deleteMutation.isPending}
            onClick={() => {
              deleteMutation.mutate(selected.id, {
                onSuccess: () => {
                  setSelectedId('');
                  onApply(EMPTY_BOARD_FILTERS);
                },
              });
            }}
            aria-label={`Удалить фильтр ${selected.name}`}
          >
            Удалить
          </button>
        </>
      ) : null}

      {saveOpen ? (
        <form className="saved-filters__form" onSubmit={(event) => void handleSave(event)}>
          <input
            value={saveName}
            onChange={(event) => setSaveName(event.target.value)}
            placeholder="Название фильтра"
            maxLength={80}
            className="board-filters__search"
            aria-label="Название сохранённого фильтра"
            autoFocus
          />
          <label className="saved-filters__default">
            <input
              type="checkbox"
              checked={saveAsDefault}
              onChange={(event) => setSaveAsDefault(event.target.checked)}
            />
            По умолчанию
          </label>
          <label className="saved-filters__default">
            <input
              type="checkbox"
              checked={saveAsShared}
              onChange={(event) => setSaveAsShared(event.target.checked)}
            />
            Общий для команды
          </label>
          <button
            type="submit"
            className="board-filters__chip board-filters__chip--active"
            disabled={!saveName.trim() || createMutation.isPending}
          >
            {createMutation.isPending ? 'Сохранение…' : 'Сохранить'}
          </button>
          <button type="button" className="board-filters__reset" onClick={() => setSaveOpen(false)}>
            Отмена
          </button>
        </form>
      ) : null}

      {createMutation.error || updateMutation.error || deleteMutation.error ? (
        <p className="saved-filters__error" role="alert">
          {(createMutation.error ?? updateMutation.error ?? deleteMutation.error)?.message ??
            'Не удалось обновить фильтр'}
        </p>
      ) : null}
    </div>
  );
}

function normalizeFilters(raw: SavedFilter['filters'] | Record<string, unknown>): BoardFilters {
  const source = raw ?? {};
  return {
    search: typeof source.search === 'string' ? source.search : '',
    priority:
      source.priority === 'LOW' ||
      source.priority === 'MEDIUM' ||
      source.priority === 'HIGH' ||
      source.priority === 'URGENT'
        ? source.priority
        : '',
    assigneeId: typeof source.assigneeId === 'string' ? source.assigneeId : '',
    tagId: typeof source.tagId === 'string' ? source.tagId : '',
    myTasksOnly: Boolean(source.myTasksOnly),
    overdueStatus:
      source.overdueStatus === 'overdue' || source.overdueStatus === 'not_overdue'
        ? source.overdueStatus
        : '',
    sprintId: typeof source.sprintId === 'string' ? source.sprintId : '',
    epicId: typeof source.epicId === 'string' ? source.epicId : '',
  };
}

// frontend/src/vue/boards/SavedFiltersControl.vue
<template>
  <div class="saved-filters">
    <select
      :value="selectedId"
      class="board-filters__select"
      aria-label="Сохранённые фильтры"
      :disabled="isLoading"
      @change="onSelect?.($event.target.value)"
    >
      <option value="">Сохранённые фильтры</option>
      <option v-for="item in saved" :key="item.id" :value="item.id">
        {{ item.isPinned ? '📌 ' : '' }}{{ item.isDefault ? '★ ' : '' }}{{ item.name
        }}{{ item.isShared ? ' · общий' : '' }}
      </option>
    </select>

    <button type="button" class="board-filters__chip" @click="saveOpen = !saveOpen">
      Сохранить фильтр
    </button>

    <template v-if="selected">
      <button
        v-if="!selected.isDefault"
        type="button"
        class="board-filters__chip"
        :disabled="updatePending"
        @click="onSetDefault?.(selected.id)"
      >
        По умолчанию
      </button>
      <button
        type="button"
        class="board-filters__chip"
        :disabled="updatePending"
        @click="onTogglePinned?.(selected.id, !selected.isPinned)"
      >
        {{ selected.isPinned ? 'Открепить' : 'Закрепить' }}
      </button>
      <button
        type="button"
        class="board-filters__chip"
        :disabled="updatePending"
        @click="onToggleShared?.(selected.id, !selected.isShared)"
      >
        {{ selected.isShared ? 'Скрыть' : 'Поделиться' }}
      </button>
      <button
        type="button"
        class="board-filters__reset"
        :disabled="deletePending"
        :aria-label="'Удалить фильтр ' + selected.name"
        @click="onDelete?.(selected.id)"
      >
        Удалить
      </button>
    </template>

    <form v-if="saveOpen" class="saved-filters__form" @submit.prevent="submitSave">
      <input
        v-model="saveName"
        placeholder="Название фильтра"
        maxlength="80"
        class="board-filters__search"
        aria-label="Название сохранённого фильтра"
        autofocus
      />
      <label class="saved-filters__default">
        <input v-model="saveAsDefault" type="checkbox" />
        По умолчанию
      </label>
      <label class="saved-filters__default">
        <input v-model="saveAsShared" type="checkbox" />
        Общий для команды
      </label>
      <button
        type="submit"
        class="board-filters__chip board-filters__chip--active"
        :disabled="!saveName.trim() || createPending"
      >
        {{ createPending ? 'Сохранение…' : 'Сохранить' }}
      </button>
      <button type="button" class="board-filters__reset" @click="saveOpen = false">Отмена</button>
    </form>

    <p v-if="error" class="saved-filters__error" role="alert">{{ error }}</p>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'

const props = defineProps({
  saved: { type: Array, default: () => [] },
  selectedId: { type: String, default: '' },
  isLoading: { type: Boolean, default: false },
  createPending: { type: Boolean, default: false },
  updatePending: { type: Boolean, default: false },
  deletePending: { type: Boolean, default: false },
  error: { type: String, default: '' },
  onSelect: { type: Function, default: null },
  onSave: { type: Function, default: null },
  onSetDefault: { type: Function, default: null },
  onTogglePinned: { type: Function, default: null },
  onToggleShared: { type: Function, default: null },
  onDelete: { type: Function, default: null },
})

const saveOpen = ref(false)
const saveName = ref('')
const saveAsDefault = ref(false)
const saveAsShared = ref(false)

const selected = computed(() => props.saved.find((item) => item.id === props.selectedId) || null)

async function submitSave() {
  const name = saveName.value.trim()
  if (!name) return
  await props.onSave?.({
    name,
    isDefault: saveAsDefault.value,
    isShared: saveAsShared.value,
  })
  saveOpen.value = false
  saveName.value = ''
  saveAsDefault.value = false
  saveAsShared.value = false
}
</script>
