// frontend/src/features/boards/components/task-drawer/task-drawer-actions.tsx
'use client';

import { useState } from 'react';
import { useDeleteTaskMutation, useDuplicateTaskMutation } from '../../hooks';
import { copyTaskLink } from '../../lib/task-link';

export function TaskDrawerActions({
  workspaceId,
  taskId,
  linkSource,
  title,
  isSaving,
  saveError,
  onOpenTask,
  onClose,
}: {
  workspaceId: string;
  taskId: string;
  linkSource: 'board' | 'all-tasks' | 'my-tasks';
  title: string;
  isSaving: boolean;
  saveError: string | null | undefined;
  onOpenTask: (taskId: string) => void;
  onClose: () => void;
}) {
  const deleteMutation = useDeleteTaskMutation(workspaceId);
  const duplicateMutation = useDuplicateTaskMutation(workspaceId);
  const [linkCopied, setLinkCopied] = useState(false);

  const handleDelete = async () => {
    await deleteMutation.mutateAsync(taskId);
    onClose();
  };

  const handleDuplicate = async () => {
    const copy = await duplicateMutation.mutateAsync(taskId);
    if (copy?.id) {
      onOpenTask(copy.id);
    }
  };

  const handleCopyLink = async () => {
    await copyTaskLink(taskId, linkSource);
    setLinkCopied(true);
    window.setTimeout(() => setLinkCopied(false), 2000);
  };

  return (
    <>
      {saveError ? <p className="text-sm text-red-400">{saveError}</p> : null}

      <div className="task-drawer__actions">
        <button type="button" onClick={handleCopyLink} className="btn-ghost">
          {linkCopied ? 'Скопировано' : 'Ссылка'}
        </button>
        <button
          type="button"
          onClick={handleDuplicate}
          disabled={duplicateMutation.isPending}
          className="btn-ghost"
        >
          {duplicateMutation.isPending ? '…' : 'Дублировать'}
        </button>
        <button
          type="button"
          onClick={handleDelete}
          disabled={deleteMutation.isPending}
          className="btn-ghost task-drawer__danger"
        >
          Удалить
        </button>
        <button type="submit" disabled={isSaving || !title.trim()} className="btn-primary">
          {isSaving ? '…' : 'Сохранить'}
        </button>
      </div>
    </>
  );
}

// frontend/src/vue/boards/TaskDrawerActions.vue
<template>
  <div>
    <p v-if="saveError" class="text-sm text-red-400">{{ saveError }}</p>

    <div class="task-drawer__actions">
      <button type="button" class="btn-ghost" @click="onCopyLink?.()">
        {{ linkCopied ? 'Скопировано' : 'Ссылка' }}
      </button>
      <button
        type="button"
        class="btn-ghost"
        :disabled="duplicatePending"
        @click="onDuplicate?.()"
      >
        {{ duplicatePending ? '…' : 'Дублировать' }}
      </button>
      <button
        type="button"
        class="btn-ghost task-drawer__danger"
        :disabled="deletePending"
        @click="onDelete?.()"
      >
        Удалить
      </button>
      <button type="submit" class="btn-primary" :disabled="isSaving || !canSave">
        {{ isSaving ? '…' : 'Сохранить' }}
      </button>
    </div>
  </div>
</template>

<script setup>
defineProps({
  isSaving: { type: Boolean, default: false },
  canSave: { type: Boolean, default: false },
  saveError: { type: String, default: '' },
  linkCopied: { type: Boolean, default: false },
  duplicatePending: { type: Boolean, default: false },
  deletePending: { type: Boolean, default: false },
  onCopyLink: { type: Function, default: null },
  onDuplicate: { type: Function, default: null },
  onDelete: { type: Function, default: null },
})
</script>
