// frontend/src/features/boards/components/task-subtasks-section.tsx
'use client';

import { useState } from 'react';
import {
  useCreateSubtaskMutation,
  useDeleteSubtaskMutation,
  useSubtasksQuery,
  useUpdateSubtaskMutation,
} from '@/features/subtasks/hooks';
import { FieldHint } from './field-hint';

export function TaskSubtasksSection({
  workspaceId,
  taskId,
}: {
  workspaceId: string;
  taskId: string;
}) {
  const { data: subtasks = [], isLoading } = useSubtasksQuery(workspaceId, taskId);
  const createMutation = useCreateSubtaskMutation(workspaceId, taskId);
  const updateMutation = useUpdateSubtaskMutation(workspaceId, taskId);
  const deleteMutation = useDeleteSubtaskMutation(workspaceId, taskId);
  const [title, setTitle] = useState('');

  const completed = subtasks.filter((item) => item.completed).length;

  return (
    <section className="task-subtasks" aria-labelledby="task-subtasks-title">
      <div className="task-subtasks__header">
        <h3 id="task-subtasks-title" className="task-drawer__section-title">
          Подзадачи
          <FieldHint text="Мелкие шаги внутри задачи. Прогресс считается по отмеченным пунктам." />
        </h3>
        <span>
          {completed}/{subtasks.length}
        </span>
      </div>

      {isLoading ? <p role="status">Загрузка подзадач...</p> : null}

      <ul className="task-subtasks__list" role="list">
        {subtasks.map((subtask) => (
          <li key={subtask.id}>
            <label>
              <input
                type="checkbox"
                checked={subtask.completed}
                disabled={updateMutation.isPending}
                onChange={(event) =>
                  updateMutation.mutate({
                    subtaskId: subtask.id,
                    data: { completed: event.target.checked },
                  })
                }
              />
              <span className={subtask.completed ? 'is-done' : undefined}>{subtask.title}</span>
            </label>
            <button
              type="button"
              aria-label={`Удалить подзадачу ${subtask.title}`}
              disabled={deleteMutation.isPending}
              onClick={() => deleteMutation.mutate(subtask.id)}
            >
              ×
            </button>
          </li>
        ))}
      </ul>

      <form
        className="task-subtasks__create"
        onSubmit={(event) => {
          event.preventDefault();
          if (!title.trim()) return;
          createMutation.mutate(title.trim(), { onSuccess: () => setTitle('') });
        }}
      >
        <input
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          placeholder="Новая подзадача"
          maxLength={200}
          aria-label="Название подзадачи"
        />
        <button type="submit" disabled={createMutation.isPending || !title.trim()}>
          Добавить
        </button>
      </form>
    </section>
  );
}

// frontend/src/vue/boards/TaskSubtasksSection.vue
<template>
  <section class="task-subtasks" aria-labelledby="task-subtasks-title">
    <div class="task-subtasks__header">
      <h3 id="task-subtasks-title" class="task-drawer__section-title">
        Подзадачи
        <FieldHint text="Мелкие шаги внутри задачи. Прогресс считается по отмеченным пунктам." />
      </h3>
      <span>{{ completed }}/{{ subtasks.length }}</span>
    </div>

    <p v-if="isLoading" role="status">Загрузка подзадач...</p>

    <ul class="task-subtasks__list" role="list">
      <li v-for="subtask in subtasks" :key="subtask.id">
        <label>
          <input
            type="checkbox"
            :checked="subtask.completed"
            :disabled="updatePending"
            @change="onToggle?.(subtask.id, $event.target.checked)"
          />
          <span :class="{ 'is-done': subtask.completed }">{{ subtask.title }}</span>
        </label>
        <button
          type="button"
          :aria-label="'Удалить подзадачу ' + subtask.title"
          :disabled="deletePending"
          @click="onDelete?.(subtask.id)"
        >
          ×
        </button>
      </li>
    </ul>

    <form class="task-subtasks__create" @submit.prevent="submit">
      <input
        v-model="title"
        placeholder="Новая подзадача"
        maxlength="200"
        aria-label="Название подзадачи"
      />
      <button type="submit" :disabled="createPending || !title.trim()">Добавить</button>
    </form>
  </section>
</template>

<script setup>
import { computed, ref } from 'vue'
import FieldHint from './FieldHint.vue'

const props = defineProps({
  subtasks: { type: Array, default: () => [] },
  isLoading: { type: Boolean, default: false },
  createPending: { type: Boolean, default: false },
  updatePending: { type: Boolean, default: false },
  deletePending: { type: Boolean, default: false },
  onToggle: { type: Function, default: null },
  onDelete: { type: Function, default: null },
  onCreate: { type: Function, default: null },
})

const title = ref('')
const completed = computed(() => props.subtasks.filter((item) => item.completed).length)

async function submit() {
  const trimmed = title.value.trim()
  if (!trimmed) return
  try {
    await props.onCreate?.(trimmed)
    title.value = ''
  } catch {
    /* handled by React */
  }
}
</script>
