// frontend/src/features/attachments/components/task-attachments-section.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { attachmentContentUrl } from '../api';
import {
  useAttachmentsQuery,
  useDeleteAttachmentMutation,
  useUploadAttachmentMutation,
} from '../hooks';
import { ATTACHMENT_ACCEPT, ATTACHMENT_MAX_BYTES, type TaskAttachment } from '../types';
import { FieldHint } from '@/features/boards/components/field-hint';

const EMPTY_ATTACHMENTS: TaskAttachment[] = [];

export function TaskAttachmentsSection({
  workspaceId,
  taskId,
}: {
  workspaceId: string;
  taskId: string;
}) {
  const inputRef = useRef<HTMLInputElement>(null);
  const { data, isLoading } = useAttachmentsQuery(workspaceId, taskId);
  const attachments = data ?? EMPTY_ATTACHMENTS;
  const uploadMutation = useUploadAttachmentMutation(workspaceId, taskId);
  const deleteMutation = useDeleteAttachmentMutation(workspaceId, taskId);
  const [error, setError] = useState('');
  const [thumbnails, setThumbnails] = useState<Record<string, string>>({});

  useEffect(() => {
    let cancelled = false;
    const objectUrls: string[] = [];

    const loadThumbs = async () => {
      const images = attachments.filter((item) => item.isImage);
      if (images.length === 0) {
        setThumbnails((prev) => (Object.keys(prev).length === 0 ? prev : {}));
        return;
      }

      const next: Record<string, string> = {};

      await Promise.all(
        images.map(async (attachment) => {
          try {
            const response = await fetch(attachmentContentUrl(workspaceId, taskId, attachment.id), {
              credentials: 'include',
            });
            if (!response.ok) return;
            const blob = await response.blob();
            const url = URL.createObjectURL(blob);
            objectUrls.push(url);
            next[attachment.id] = url;
          } catch {
            /* ignore */
          }
        }),
      );

      if (!cancelled) setThumbnails(next);
    };

    void loadThumbs();

    return () => {
      cancelled = true;
      objectUrls.forEach((url) => URL.revokeObjectURL(url));
    };
  }, [attachments, taskId, workspaceId]);

  const openContent = (attachment: TaskAttachment) => {
    window.open(attachmentContentUrl(workspaceId, taskId, attachment.id), '_blank', 'noopener');
  };

  const handleFiles = async (files: FileList | null) => {
    if (!files?.length) return;
    setError('');
    const file = files[0];
    if (file.size > ATTACHMENT_MAX_BYTES) {
      setError('Максимальный размер файла — 5 МБ');
      return;
    }
    try {
      await uploadMutation.mutateAsync(file);
    } catch (uploadError) {
      setError(uploadError instanceof Error ? uploadError.message : 'Не удалось загрузить файл');
    } finally {
      if (inputRef.current) inputRef.current.value = '';
    }
  };

  return (
    <section className="task-subtasks task-attachments" aria-labelledby="task-attachments-title">
      <div className="task-subtasks__header">
        <h3 id="task-attachments-title" className="task-drawer__section-title">
          Вложения
          <FieldHint text="Файлы к задаче: изображения, PDF или TXT до 5 МБ." />
        </h3>
        <span>{attachments.length}</span>
      </div>

      {isLoading ? <p role="status">Загрузка вложений...</p> : null}

      {attachments.length === 0 && !isLoading ? (
        <p className="task-tags__empty">Пока нет файлов</p>
      ) : (
        <ul className="task-attachments__list" role="list">
          {attachments.map((attachment) => (
            <li key={attachment.id}>
              {attachment.isImage && thumbnails[attachment.id] ? (
                <button
                  type="button"
                  className="task-attachments__thumb"
                  onClick={() => openContent(attachment)}
                  aria-label={`Открыть ${attachment.originalName}`}
                >
                  <img src={thumbnails[attachment.id]} alt="" />
                </button>
              ) : (
                <button
                  type="button"
                  className="task-attachments__file"
                  onClick={() => openContent(attachment)}
                >
                  <span aria-hidden="true">
                    {attachment.isImage ? 'IMG' : attachment.isPdf ? 'PDF' : 'TXT'}
                  </span>
                  <span>{attachment.originalName}</span>
                </button>
              )}
              <button
                type="button"
                aria-label={`Удалить ${attachment.originalName}`}
                disabled={deleteMutation.isPending}
                onClick={() => deleteMutation.mutate(attachment.id)}
              >
                ×
              </button>
            </li>
          ))}
        </ul>
      )}

      <div className="task-subtasks__create">
        <input
          ref={inputRef}
          type="file"
          accept={ATTACHMENT_ACCEPT}
          className="sr-only"
          id={`task-attachment-upload-${taskId}`}
          onChange={(event) => void handleFiles(event.target.files)}
        />
        <label htmlFor={`task-attachment-upload-${taskId}`} className="task-attachments__upload">
          {uploadMutation.isPending ? 'Загрузка…' : 'Загрузить файл'}
        </label>
      </div>

      {error || uploadMutation.error || deleteMutation.error ? (
        <p className="text-sm text-red-400" role="alert">
          {error ||
            uploadMutation.error?.message ||
            deleteMutation.error?.message ||
            'Ошибка вложений'}
        </p>
      ) : null}
      <p className="task-attachments__hint">Изображения, PDF или TXT до 5 МБ</p>
    </section>
  );
}

// frontend/src/vue/boards/TaskAttachmentsSection.vue
<template>
  <section class="task-subtasks task-attachments" aria-labelledby="task-attachments-title">
    <div class="task-subtasks__header">
      <h3 id="task-attachments-title" class="task-drawer__section-title">
        Вложения
        <FieldHint text="Файлы к задаче: изображения, PDF или TXT до 5 МБ." />
      </h3>
      <span>{{ attachments.length }}</span>
    </div>

    <p v-if="isLoading" role="status">Загрузка вложений...</p>

    <p v-else-if="attachments.length === 0" class="task-tags__empty">Пока нет файлов</p>

    <ul v-else class="task-attachments__list" role="list">
      <li v-for="attachment in attachments" :key="attachment.id">
        <button
          v-if="attachment.isImage && thumbnails[attachment.id]"
          type="button"
          class="task-attachments__thumb"
          :aria-label="'Открыть ' + attachment.originalName"
          @click="onOpen?.(attachment.id)"
        >
          <img :src="thumbnails[attachment.id]" alt="" />
        </button>
        <button
          v-else
          type="button"
          class="task-attachments__file"
          @click="onOpen?.(attachment.id)"
        >
          <span aria-hidden="true">
            {{ attachment.isImage ? 'IMG' : attachment.isPdf ? 'PDF' : 'TXT' }}
          </span>
          <span>{{ attachment.originalName }}</span>
        </button>
        <button
          type="button"
          :aria-label="'Удалить ' + attachment.originalName"
          :disabled="deletePending"
          @click="onDelete?.(attachment.id)"
        >
          ×
        </button>
      </li>
    </ul>

    <div class="task-subtasks__create">
      <input
        :id="inputId"
        ref="fileInput"
        type="file"
        :accept="accept"
        class="sr-only"
        @change="onFileChange"
      />
      <label :for="inputId" class="task-attachments__upload">
        {{ uploadPending ? 'Загрузка…' : 'Загрузить файл' }}
      </label>
    </div>

    <p v-if="error" class="text-sm text-red-400" role="alert">{{ error }}</p>
    <p class="task-attachments__hint">Изображения, PDF или TXT до 5 МБ</p>
  </section>
</template>

<script setup>
import { computed, ref } from 'vue'
import FieldHint from './FieldHint.vue'

const props = defineProps({
  taskId: { type: String, required: true },
  attachments: { type: Array, default: () => [] },
  thumbnails: { type: Object, default: () => ({}) },
  accept: { type: String, required: true },
  isLoading: { type: Boolean, default: false },
  uploadPending: { type: Boolean, default: false },
  deletePending: { type: Boolean, default: false },
  error: { type: String, default: '' },
  onOpen: { type: Function, default: null },
  onDelete: { type: Function, default: null },
  onUpload: { type: Function, default: null },
})

const fileInput = ref(null)
const inputId = computed(() => 'task-attachment-upload-' + props.taskId)

function onFileChange(event) {
  const files = event.target.files
  props.onUpload?.(files)
  if (fileInput.value) fileInput.value.value = ''
}
</script>
