// frontend/src/features/auth/components/register-form.tsx
'use client';

import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import { useRegisterMutation } from '../hooks';

export function RegisterForm() {
  const router = useRouter();
  const registerMutation = useRegisterMutation();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    await registerMutation.mutateAsync({
      name,
      email,
      password,
    });
    router.push('/onboarding');
    router.refresh();
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="space-y-1.5">
        <label htmlFor="name" className="tt-auth__label">
          Имя
        </label>
        <input
          id="name"
          required
          value={name}
          onChange={(event) => setName(event.target.value)}
          className="glass-input"
        />
      </div>

      <div className="space-y-1.5">
        <label htmlFor="email" className="tt-auth__label">
          Email
        </label>
        <input
          id="email"
          type="email"
          required
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          className="glass-input"
        />
      </div>

      <div className="space-y-1.5">
        <label htmlFor="password" className="tt-auth__label">
          Пароль
        </label>
        <input
          id="password"
          type="password"
          required
          minLength={8}
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          className="glass-input"
        />
      </div>

      {registerMutation.error ? (
        <p className="text-sm text-red-400">{registerMutation.error.message}</p>
      ) : null}

      <button type="submit" disabled={registerMutation.isPending} className="btn-primary w-full">
        {registerMutation.isPending ? 'Создание...' : 'Создать аккаунт'}
      </button>
    </form>
  );
}

// frontend/src/vue/auth/RegisterForm.vue
<template>
  <form class="space-y-4" @submit.prevent="submit">
    <div class="space-y-1.5">
      <label for="name" class="tt-auth__label">Имя</label>
      <input
        id="name"
        v-model="name"
        required
        class="glass-input"
        autocomplete="name"
      />
    </div>

    <div class="space-y-1.5">
      <label for="email" class="tt-auth__label">Email</label>
      <input
        id="email"
        v-model="email"
        type="email"
        required
        class="glass-input"
        autocomplete="email"
      />
    </div>

    <div class="space-y-1.5">
      <label for="password" class="tt-auth__label">Пароль</label>
      <input
        id="password"
        v-model="password"
        type="password"
        required
        minlength="8"
        class="glass-input"
        autocomplete="new-password"
      />
    </div>

    <p v-if="error" class="text-sm text-red-400">{{ error }}</p>

    <button type="submit" class="btn-primary w-full" :disabled="pending">
      {{ pending ? 'Создание...' : 'Создать аккаунт' }}
    </button>
  </form>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  pending: { type: Boolean, default: false },
  error: { type: String, default: '' },
  onSubmit: { type: Function, default: null },
})

const name = ref('')
const email = ref('')
const password = ref('')

async function submit() {
  await props.onSubmit?.({
    name: name.value,
    email: email.value,
    password: password.value,
  })
}
</script>
