// frontend/src/features/workspaces/components/create-workspace-form.tsx
'use client';

import { FormEvent, useState } from 'react';
import { useCreateWorkspaceMutation } from '../hooks';

export function CreateWorkspaceForm() {
  const [name, setName] = useState('');
  const createMutation = useCreateWorkspaceMutation();

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    await createMutation.mutateAsync({ name });
    setName('');
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-wrap gap-2">
      <input
        value={name}
        onChange={(event) => setName(event.target.value)}
        placeholder="Название новой команды"
        required
        className="glass-input min-w-[220px] flex-1"
      />
      <button type="submit" disabled={createMutation.isPending} className="btn-ghost">
        Создать команду
      </button>
    </form>
  );
}

// frontend/src/vue/workspaces/CreateWorkspaceForm.vue
<template>
  <form class="flex flex-wrap gap-2" @submit.prevent="onSubmit">
    <input
      v-model="name"
      required
      placeholder="Название новой команды"
      class="glass-input min-w-[220px] flex-1"
    />
    <button type="submit" class="btn-ghost" :disabled="isPending">
      {{ isPending ? 'Создание...' : 'Создать команду' }}
    </button>
  </form>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  isPending: { type: Boolean, default: false },
  onCreate: { type: Function, required: true },
})

const name = ref('')

async function onSubmit() {
  const trimmed = name.value.trim()
  if (!trimmed) return

  try {
    await props.onCreate({ name: trimmed })
    name.value = ''
  } catch {
    /* ignore */
  }
}
</script>
