// frontend/src/features/shell/components/app-sidebar.tsx
'use client';

import { motion } from 'framer-motion';
import type { LucideIcon } from 'lucide-react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { BrandLogo } from '@/components/marketing/brand-logo';
import { cn } from '@/shared/lib/cn';

export interface NavItem {
  href: string;
  label: string;
  icon: LucideIcon;
  hidden?: boolean;
}

export interface NavGroup {
  id: string;
  label: string;
  items: NavItem[];
}

interface AppSidebarProps {
  groups: NavGroup[];
  collapsed: boolean;
  onToggleCollapse: () => void;
  CollapseIcon: LucideIcon;
}

export function AppSidebar({ groups, collapsed, onToggleCollapse, CollapseIcon }: AppSidebarProps) {
  const pathname = usePathname();

  const isActive = (href: string) => {
    if (href === '/dashboard') return pathname === '/dashboard';
    return pathname === href || pathname.startsWith(`${href}/`);
  };

  return (
    <aside className="app-sidebar" aria-label="Боковая навигация">
      <div className="app-sidebar__brand">
        <BrandLogo href="/dashboard" />
        <button
          type="button"
          className="app-sidebar__collapse"
          onClick={onToggleCollapse}
          aria-label={collapsed ? 'Развернуть меню' : 'Свернуть меню'}
          title={collapsed ? 'Развернуть' : 'Свернуть'}
        >
          <CollapseIcon size={16} strokeWidth={1.75} />
        </button>
      </div>

      <nav className="app-sidebar__nav">
        {groups.map((group) => {
          const visible = group.items.filter((item) => !item.hidden);
          if (visible.length === 0) return null;
          return (
            <div key={group.id}>
              <p className="app-sidebar__group-label">{group.label}</p>
              <div className="app-sidebar__links">
                {visible.map((item) => {
                  const Icon = item.icon;
                  const active = isActive(item.href);
                  return (
                    <Link
                      key={item.href}
                      href={item.href}
                      className={cn('app-sidebar__link', active && 'app-sidebar__link--active')}
                      aria-current={active ? 'page' : undefined}
                      title={collapsed ? item.label : undefined}
                    >
                      {active ? (
                        <motion.span
                          layoutId="nav-ink"
                          className="sr-only"
                          transition={{ type: 'spring', stiffness: 420, damping: 34 }}
                        />
                      ) : null}
                      <Icon size={17} strokeWidth={1.75} aria-hidden="true" />
                      <span>{item.label}</span>
                    </Link>
                  );
                })}
              </div>
            </div>
          );
        })}
      </nav>
    </aside>
  );
}

// frontend/src/vue/shell/AppSidebar.vue
<template>
  <aside class="app-sidebar" aria-label="Боковая навигация">
    <div class="app-sidebar__brand">
      <BrandLogo href="/dashboard" />
      <button
        type="button"
        class="app-sidebar__collapse"
        :aria-label="collapsed ? 'Развернуть меню' : 'Свернуть меню'"
        :title="collapsed ? 'Развернуть' : 'Свернуть'"
        @click="onToggleCollapse?.()"
      >
        <ShellIcon :name="collapsed ? 'panel-open' : 'panel-close'" :size="16" />
      </button>
    </div>

    <nav class="app-sidebar__nav">
      <div
        v-for="group in visibleGroups"
        :key="group.id"
        class="app-sidebar__group"
        :class="{
          'app-sidebar__group--collapsible': group.collapsible,
          'app-sidebar__group--open': group.open,
        }"
      >
        <button
          v-if="group.collapsible && !collapsed"
          type="button"
          class="app-sidebar__group-toggle"
          :aria-expanded="group.open"
          :aria-controls="'nav-group-' + group.id"
          @click="onToggleGroup?.(group.id)"
        >
          <span class="app-sidebar__group-label">{{ group.label }}</span>
          <ShellIcon name="chevron-down" class="app-sidebar__group-chevron" :size="14" :stroke-width="2" />
        </button>
        <p v-else class="app-sidebar__group-label">{{ group.label }}</p>

        <div
          :id="'nav-group-' + group.id"
          class="app-sidebar__links"
          :hidden="!group.open"
          :role="group.collapsible ? 'region' : undefined"
          :aria-label="group.collapsible ? group.label : undefined"
        >
          <a
            v-for="item in group.items"
            :key="group.id + '-' + item.href"
            :href="item.href"
            class="app-sidebar__link"
            :class="{ 'app-sidebar__link--active': item.active }"
            :aria-current="item.active ? 'page' : undefined"
            :title="collapsed ? item.label : undefined"
          >
            <ShellIcon :name="item.iconKey" :size="17" />
            <span>{{ item.label }}</span>
          </a>
        </div>
      </div>
    </nav>
  </aside>
</template>

<script setup>
import { computed } from 'vue'
import BrandLogo from '../marketing/BrandLogo.vue'
import ShellIcon from './ShellIcon.vue'

const props = defineProps({
  groups: { type: Array, default: () => [] },
  collapsed: { type: Boolean, default: false },
  onToggleCollapse: { type: Function, default: null },
  onToggleGroup: { type: Function, default: null },
})

const visibleGroups = computed(() =>
  props.groups
    .map((group) => ({
      ...group,
      items: (group.items || []).filter((item) => !item.hidden),
    }))
    .filter((group) => group.items.length > 0),
)
</script>
