// frontend/src/vue/boards/BoardSwitcher.vue
<template>
  <div class="board-switcher">
    <select
      :value="boardId || ''"
      class="board-filters__select"
      aria-label="Доска"
      :disabled="isLoading || boards.length === 0"
      @change="onBoardChange?.($event.target.value)"
    >
      <option v-for="board in boards" :key="board.id" :value="board.id">
        {{ board.name }}
      </option>
    </select>

    <button type="button" class="board-filters__chip" @click="startCreate">Новая доска</button>

    <button v-if="selected" type="button" class="board-filters__chip" @click="startRename">
      Переименовать
    </button>

    <button
      v-if="boards.length > 1 && boardId"
      type="button"
      class="board-filters__reset"
      :disabled="deletePending"
      @click="onDelete?.()"
    >
      Удалить
    </button>

    <form v-if="creating" class="board-switcher__form" @submit.prevent="submitCreate">
      <input
        v-model="newName"
        placeholder="Название доски"
        maxlength="80"
        class="glass-input"
        autofocus
      />
      <select v-model="templateId" class="board-filters__select" aria-label="Шаблон доски">
        <option v-for="template in templateOptions" :key="template.id" :value="template.id">
          {{ template.name }}
        </option>
      </select>
      <button type="submit" class="btn-primary" :disabled="createPending">Создать</button>
      <button type="button" class="btn-ghost" @click="cancelCreate">Отмена</button>
    </form>

    <form v-if="renaming" class="board-switcher__form" @submit.prevent="submitRename">
      <input
        v-model="renameValue"
        placeholder="Название доски"
        maxlength="80"
        class="board-filters__search"
        aria-label="Новое название доски"
        autofocus
      />
      <button
        type="submit"
        class="board-filters__chip board-filters__chip--active"
        :disabled="!renameValue.trim() || updatePending"
      >
        Сохранить
      </button>
      <button type="button" class="board-filters__reset" @click="renaming = false">Отмена</button>
    </form>

    <p v-if="error" class="board-switcher__error" role="alert">{{ error }}</p>
  </div>
</template>

<script setup>
import { computed, ref, watch } from 'vue'

const props = defineProps({
  boards: { type: Array, default: () => [] },
  boardId: { type: String, default: '' },
  isLoading: { type: Boolean, default: false },
  templates: { type: Array, default: () => [] },
  createPending: { type: Boolean, default: false },
  updatePending: { type: Boolean, default: false },
  deletePending: { type: Boolean, default: false },
  error: { type: String, default: '' },
  onBoardChange: { type: Function, default: null },
  onCreate: { type: Function, default: null },
  onRename: { type: Function, default: null },
  onDelete: { type: Function, default: null },
  onRequestTemplates: { type: Function, default: null },
})

const creating = ref(false)
const renaming = ref(false)
const newName = ref('')
const renameValue = ref('')
const templateId = ref('kanban')

const selected = computed(() => props.boards.find((board) => board.id === props.boardId) || null)
const templateOptions = computed(() =>
  props.templates.length ? props.templates : [{ id: 'kanban', name: 'Канбан' }],
)

watch(creating, (open) => {
  if (open) props.onRequestTemplates?.()
})

function startCreate() {
  creating.value = true
  renaming.value = false
}

function cancelCreate() {
  creating.value = false
  newName.value = ''
}

function startRename() {
  if (!selected.value) return
  renaming.value = true
  creating.value = false
  renameValue.value = selected.value.name
}

async function submitCreate() {
  await props.onCreate?.(newName.value.trim() || 'Новая доска', templateId.value)
  creating.value = false
  newName.value = ''
  templateId.value = 'kanban'
}

async function submitRename() {
  if (!renameValue.value.trim()) return
  await props.onRename?.(renameValue.value.trim())
  renaming.value = false
}
</script>

// frontend/src/features/boards/components/board-switcher.tsx
'use client';

import { FormEvent, useEffect, useState } from 'react';
import { fetchBoardTemplates, type BoardTemplate } from '@/features/workspace-tools/api';
import {
  useBoardsQuery,
  useCreateBoardMutation,
  useDeleteBoardMutation,
  useUpdateBoardMutation,
} from '../hooks';

const selectedBoardStorageKey = (workspaceId: string) => `board:selected:${workspaceId}`;

export function readStoredBoardId(workspaceId: string): string | null {
  try {
    return window.localStorage.getItem(selectedBoardStorageKey(workspaceId));
  } catch {
    return null;
  }
}

export function storeSelectedBoardId(workspaceId: string, boardId: string) {
  try {
    window.localStorage.setItem(selectedBoardStorageKey(workspaceId), boardId);
  } catch (error) {
    console.warn('Не удалось сохранить выбранную доску', error);
  }
}

interface BoardSwitcherProps {
  workspaceId: string;
  boardId: string | null;
  onBoardChange: (boardId: string) => void;
}

export function BoardSwitcher({ workspaceId, boardId, onBoardChange }: BoardSwitcherProps) {
  const { data: boards = [], isLoading } = useBoardsQuery(workspaceId);
  const createMutation = useCreateBoardMutation(workspaceId);
  const updateMutation = useUpdateBoardMutation(workspaceId);
  const deleteMutation = useDeleteBoardMutation(workspaceId);
  const [creating, setCreating] = useState(false);
  const [newName, setNewName] = useState('');
  const [templateId, setTemplateId] = useState('kanban');
  const [templates, setTemplates] = useState<BoardTemplate[]>([]);
  const [renaming, setRenaming] = useState(false);
  const [renameValue, setRenameValue] = useState('');

  useEffect(() => {
    if (!creating) return;
    void fetchBoardTemplates(workspaceId)
      .then((response) => setTemplates(response.data ?? []))
      .catch(() => setTemplates([]));
  }, [creating, workspaceId]);

  useEffect(() => {
    if (!boards.length) return;
    const stored = readStoredBoardId(workspaceId);
    const exists = stored && boards.some((board) => board.id === stored);
    const nextId = exists ? stored! : boards[0].id;
    if (boardId !== nextId) {
      onBoardChange(nextId);
    }
  }, [boardId, boards, onBoardChange, workspaceId]);

  const selected = boards.find((board) => board.id === boardId) ?? null;

  const handleCreate = async (event: FormEvent) => {
    event.preventDefault();
    const name = newName.trim() || 'Новая доска';
    const created = await createMutation.mutateAsync({ name, templateId });
    setCreating(false);
    setNewName('');
    setTemplateId('kanban');
    if (created?.id) onBoardChange(created.id);
  };

  const handleRename = async (event: FormEvent) => {
    event.preventDefault();
    if (!boardId || !renameValue.trim()) return;
    await updateMutation.mutateAsync({ boardId, name: renameValue.trim() });
    setRenaming(false);
  };

  const handleDelete = async () => {
    if (!boardId || boards.length <= 1) return;
    if (!window.confirm('Удалить эту доску? Задачи на ней будут удалены.')) return;
    const remaining = boards.filter((board) => board.id !== boardId);
    await deleteMutation.mutateAsync(boardId);
    if (remaining[0]) onBoardChange(remaining[0].id);
  };

  return (
    <div className="board-switcher">
      <select
        value={boardId ?? ''}
        onChange={(event) => onBoardChange(event.target.value)}
        className="board-filters__select"
        aria-label="Доска"
        disabled={isLoading || !boards.length}
      >
        {boards.map((board) => (
          <option key={board.id} value={board.id}>
            {board.name}
          </option>
        ))}
      </select>

      <button
        type="button"
        className="board-filters__chip"
        onClick={() => {
          setCreating(true);
          setRenaming(false);
        }}
      >
        Новая доска
      </button>

      {selected ? (
        <button
          type="button"
          className="board-filters__chip"
          onClick={() => {
            setRenaming(true);
            setCreating(false);
            setRenameValue(selected.name);
          }}
        >
          Переименовать
        </button>
      ) : null}

      {boards.length > 1 && boardId ? (
        <button
          type="button"
          className="board-filters__reset"
          disabled={deleteMutation.isPending}
          onClick={() => void handleDelete()}
        >
          Удалить
        </button>
      ) : null}

      {creating ? (
        <form className="board-switcher__form" onSubmit={(event) => void handleCreate(event)}>
          <input
            value={newName}
            onChange={(event) => setNewName(event.target.value)}
            placeholder="Название доски"
            maxLength={80}
            className="glass-input"
            autoFocus
          />
          <select
            value={templateId}
            onChange={(event) => setTemplateId(event.target.value)}
            className="board-filters__select"
            aria-label="Шаблон доски"
          >
            {(templates.length ? templates : [{ id: 'kanban', name: 'Канбан' }]).map((template) => (
              <option key={template.id} value={template.id}>
                {template.name}
              </option>
            ))}
          </select>
          <button type="submit" className="btn-primary" disabled={createMutation.isPending}>
            Создать
          </button>
          <button
            type="button"
            className="btn-ghost"
            onClick={() => {
              setCreating(false);
              setNewName('');
            }}
          >
            Отмена
          </button>
        </form>
      ) : null}

      {renaming ? (
        <form className="board-switcher__form" onSubmit={(event) => void handleRename(event)}>
          <input
            value={renameValue}
            onChange={(event) => setRenameValue(event.target.value)}
            placeholder="Название доски"
            maxLength={80}
            className="board-filters__search"
            aria-label="Новое название доски"
            autoFocus
          />
          <button
            type="submit"
            className="board-filters__chip board-filters__chip--active"
            disabled={!renameValue.trim() || updateMutation.isPending}
          >
            Сохранить
          </button>
          <button type="button" className="board-filters__reset" onClick={() => setRenaming(false)}>
            Отмена
          </button>
        </form>
      ) : null}

      {createMutation.error || updateMutation.error || deleteMutation.error ? (
        <p className="board-switcher__error" role="alert">
          {(createMutation.error ?? updateMutation.error ?? deleteMutation.error)?.message}
        </p>
      ) : null}
    </div>
  );
}
