// frontend/src/vue/analytics/StuckTasksCard.vue
<template>
  <section class="stuck-tasks-card">
    <header class="stuck-tasks-card__head">
      <div>
        <p class="stuck-tasks-card__eyebrow">Здоровье доски</p>
        <h2>Застрявшие задачи</h2>
        <p class="stuck-tasks-card__hint">
          Открытые задачи без обновлений дольше порога (прокси «без движения»).
        </p>
      </div>
      <div class="stuck-tasks-card__controls">
        <label>
          Порог
          <select class="glass-input" :value="days" @change="onDaysChange($event.target.value)">
            <option v-for="value in dayOptions" :key="value" :value="value">
              {{ value }} дн.
            </option>
          </select>
        </label>
        <button
          v-if="aiConfigured"
          type="button"
          class="btn-ghost"
          :disabled="insightPending || isLoading"
          @click="onRequestInsight?.()"
        >
          {{ insightPending ? 'ИИ думает…' : 'Разбор ИИ' }}
        </button>
      </div>
    </header>

    <p v-if="isLoading" class="stuck-tasks-card__hint">Загрузка…</p>
    <p v-else-if="isError" class="stuck-tasks-card__error">Не удалось загрузить список</p>
    <p v-else-if="tasks.length === 0" class="stuck-tasks-card__empty">
      Нет застрявших задач за выбранный порог.
    </p>
    <template v-else>
      <p class="stuck-tasks-card__count">
        Найдено: {{ count }}{{ truncated ? ' (показаны первые 50)' : '' }}
      </p>
      <div class="stuck-tasks-card__table-wrap">
        <table class="stuck-tasks-card__table">
          <thead>
            <tr>
              <th>Задача</th>
              <th>Колонка</th>
              <th>Исполнитель</th>
              <th>Дней без обновлений</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="task in tasks" :key="task.id">
              <td>{{ task.title }}</td>
              <td>{{ task.columnName }}</td>
              <td>{{ task.assigneeName }}</td>
              <td>{{ task.daysSinceUpdate }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>

    <p v-if="insightError" class="stuck-tasks-card__error">{{ insightError }}</p>
    <div v-if="insight" class="stuck-tasks-card__insight">{{ insight }}</div>
  </section>
</template>

<script setup>
const props = defineProps({
  days: { type: Number, required: true },
  dayOptions: { type: Array, default: () => [3, 5, 7, 14] },
  aiConfigured: { type: Boolean, default: false },
  isLoading: { type: Boolean, default: false },
  isError: { type: Boolean, default: false },
  insightPending: { type: Boolean, default: false },
  count: { type: Number, default: 0 },
  truncated: { type: Boolean, default: false },
  tasks: { type: Array, default: () => [] },
  insight: { type: String, default: null },
  insightError: { type: String, default: null },
  onDaysChange: { type: Function, default: null },
  onRequestInsight: { type: Function, default: null },
})

function onDaysChange(value) {
  props.onDaysChange?.(Number(value))
}
</script>

// frontend/src/features/analytics/components/stuck-tasks-card.tsx
'use client';

import { useState } from 'react';
import { useAiSettingsQuery } from '@/features/ai';
import { useStuckTasksInsightMutation, useStuckTasksQuery } from '../hooks';

const DAY_OPTIONS = [3, 5, 7, 14];

export function StuckTasksCard({
  workspaceId,
  assigneeId,
}: {
  workspaceId: string;
  assigneeId?: string;
}) {
  const [days, setDays] = useState(5);
  const params = { days, assigneeId: assigneeId || undefined };
  const stuckQuery = useStuckTasksQuery(workspaceId, params);
  const { data: aiSettings } = useAiSettingsQuery(workspaceId);
  const insightMutation = useStuckTasksInsightMutation(workspaceId);
  const [insight, setInsight] = useState<string | null>(null);
  const [insightError, setInsightError] = useState<string | null>(null);

  const data = stuckQuery.data;
  const tasks = data?.tasks ?? [];

  const handleInsight = async () => {
    setInsightError(null);
    try {
      const result = await insightMutation.mutateAsync(params);
      setInsight(result.insight);
    } catch (err) {
      setInsightError(err instanceof Error ? err.message : 'Не удалось получить разбор');
    }
  };

  return (
    <section className="stuck-tasks-card">
      <header className="stuck-tasks-card__head">
        <div>
          <p className="stuck-tasks-card__eyebrow">Здоровье доски</p>
          <h2>Застрявшие задачи</h2>
          <p className="stuck-tasks-card__hint">
            Открытые задачи без обновлений дольше порога (прокси «без движения»).
          </p>
        </div>
        <div className="stuck-tasks-card__controls">
          <label>
            Порог
            <select
              className="glass-input"
              value={days}
              onChange={(event) => {
                setDays(Number(event.target.value));
                setInsight(null);
                setInsightError(null);
              }}
            >
              {DAY_OPTIONS.map((value) => (
                <option key={value} value={value}>
                  {value} дн.
                </option>
              ))}
            </select>
          </label>
          {aiSettings?.configured ? (
            <button
              type="button"
              className="btn-ghost"
              disabled={insightMutation.isPending || stuckQuery.isLoading}
              onClick={() => void handleInsight()}
            >
              {insightMutation.isPending ? 'ИИ думает…' : 'Разбор ИИ'}
            </button>
          ) : null}
        </div>
      </header>

      {stuckQuery.isLoading ? (
        <p className="stuck-tasks-card__hint">Загрузка…</p>
      ) : stuckQuery.isError ? (
        <p className="stuck-tasks-card__error">Не удалось загрузить список</p>
      ) : tasks.length === 0 ? (
        <p className="stuck-tasks-card__empty">Нет застрявших задач за выбранный порог.</p>
      ) : (
        <>
          <p className="stuck-tasks-card__count">
            Найдено: {data?.count}
            {data?.truncated ? ' (показаны первые 50)' : ''}
          </p>
          <div className="stuck-tasks-card__table-wrap">
            <table className="stuck-tasks-card__table">
              <thead>
                <tr>
                  <th>Задача</th>
                  <th>Колонка</th>
                  <th>Исполнитель</th>
                  <th>Дней без обновлений</th>
                </tr>
              </thead>
              <tbody>
                {tasks.map((task) => (
                  <tr key={task.id}>
                    <td>{task.title}</td>
                    <td>{task.columnName}</td>
                    <td>{task.assignee?.name ?? '—'}</td>
                    <td>{task.daysSinceUpdate}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {insightError ? <p className="stuck-tasks-card__error">{insightError}</p> : null}
      {insight ? <div className="stuck-tasks-card__insight">{insight}</div> : null}
    </section>
  );
}
